/**
 * @otis/ledger/commands/undo
 * Grouped suffix ("from here") and single-action undo preview and commit.
 * In accordance with architecture.md section 10 and plans/002-ledger.md.
 */

import type {
  ActionReceipt,
  CommandResult,
  LedgerEvent,
  UndoMode,
  UndoPreview,
  UndoPreviewDependency,
  UndoRequest,
} from '@otis/contracts';
import type { LedgerCommandContext, LedgerProjectionState } from '../types.js';
import { createLedgerEvent } from './events.js';
import { rebuildProjections } from '../reducers/rebuild.js';

export function computeUndoPreview(
  targetActionId: string,
  mode: UndoMode,
  allActions: ActionReceipt[],
  allEvents: LedgerEvent[],
  currentState: LedgerProjectionState,
  expectedRevision: number,
): UndoPreview {
  // 1. Locate target action receipt
  const targetIndex = allActions.findIndex((a) => a.action_id === targetActionId);
  if (targetIndex === -1) {
    throw new Error(`Action receipt '${targetActionId}' not found.`);
  }
  const targetAction = allActions[targetIndex]!;

  // 2. Select actions according to mode
  const selectedActionIds: string[] = [];
  if (mode === 'single') {
    selectedActionIds.push(targetAction.action_id);
  } else {
    // mode === 'from_here':
    // Select the referenced successful action and later successful business actions in the SAME run
    if (targetAction.run_id) {
      for (let i = targetIndex; i < allActions.length; i++) {
        const a = allActions[i]!;
        if (a.run_id === targetAction.run_id && a.result_status === 'applied') {
          selectedActionIds.push(a.action_id);
        }
      }
    } else {
      selectedActionIds.push(targetAction.action_id);
    }
  }

  const selectedActionSet = new Set(selectedActionIds);

  // 2b. Identify all events that are already reverted
  const alreadyRevertedEventIds = new Set<string>();
  for (const evt of allEvents) {
    if (evt.kind === 'revert' && evt.reverts_event_id) {
      alreadyRevertedEventIds.add(evt.reverts_event_id);
    }
  }

  // 3. Find active events generated by selected actions
  const selectedEventIds: string[] = [];
  const createdEntityIds = new Set<string>();
  const createdTaskIds = new Set<string>();

  for (const evt of allEvents) {
    if (selectedActionSet.has(evt.action_id)) {
      // An event is active only if it is not a revert event itself and has not already been reverted
      if (evt.kind !== 'revert' && !alreadyRevertedEventIds.has(evt.id)) {
        selectedEventIds.push(evt.id);
        if (evt.kind === 'entity_created' && evt.entity_id) {
          createdEntityIds.add(evt.entity_id);
        }
        if (evt.kind === 'task_created') {
          const payload = evt.payload as { task_id: string };
          if (payload.task_id) createdTaskIds.add(payload.task_id);
        }
      }
    }
  }

  // 4. Dependency Analysis:
  // Detect if actions in later/different runs depend on resources modified by selected actions
  const dependencies: UndoPreviewDependency[] = [];
  for (const evt of allEvents) {
    if (!selectedActionSet.has(evt.action_id)) {
      // Check if later action references an entity or task created by an action being undone
      if (evt.entity_id && createdEntityIds.has(evt.entity_id)) {
        dependencies.push({
          action_id: evt.action_id,
          reason: `Later action modified entity '${evt.entity_id}' that would be undone.`,
          requires_clarification: true,
        });
      }
      if (evt.kind === 'task_updated' || evt.kind === 'task_done' || evt.kind === 'task_cancelled') {
        const payload = evt.payload as { task_id?: string };
        if (payload.task_id && createdTaskIds.has(payload.task_id)) {
          dependencies.push({
            action_id: evt.action_id,
            reason: `Later action modified task '${payload.task_id}' that would be undone.`,
            requires_clarification: true,
          });
        }
      }
      if (evt.supersedes_event_id && selectedEventIds.includes(evt.supersedes_event_id)) {
        dependencies.push({
          action_id: evt.action_id,
          reason: `Later action supersedes an event that would be undone.`,
          requires_clarification: true,
        });
      }
    }
  }

  // Deduplicate dependencies by action_id
  const uniqueDeps: UndoPreviewDependency[] = [];
  const seenActionIds = new Set<string>();
  for (const d of dependencies) {
    if (!seenActionIds.has(d.action_id)) {
      seenActionIds.add(d.action_id);
      uniqueDeps.push(d);
    }
  }

  // 5. Simulate rebuild with selected events suppressed to determine affected records
  const selectedEventSet = new Set(selectedEventIds);
  const simulatedEvents = allEvents.filter((e) => !selectedEventSet.has(e.id));
  const simulatedState = rebuildProjections(simulatedEvents);

  const affectedEntities: { id: string; name: string; changes: string[] }[] = [];
  for (const [id, currentEntity] of currentState.entities) {
    const simEntity = simulatedState.entities.get(id);
    const changes: string[] = [];
    if (!simEntity) {
      if (createdEntityIds.has(id)) {
        changes.push(`Entity '${currentEntity.name}' will be removed.`);
      }
    } else {
      if (simEntity.name !== currentEntity.name) {
        changes.push(`Name will revert from '${currentEntity.name}' to '${simEntity.name}'.`);
      }
      if (simEntity.status !== currentEntity.status) {
        changes.push(`Status will revert from '${currentEntity.status}' to '${simEntity.status}'.`);
      }
    }
    if (changes.length > 0) {
      affectedEntities.push({ id, name: currentEntity.name, changes });
    }
  }

  const affectedTasks: { id: string; title: string; changes: string[] }[] = [];
  for (const [id, currentTask] of currentState.tasks) {
    const simTask = simulatedState.tasks.get(id);
    const changes: string[] = [];
    if (!simTask) {
      if (createdTaskIds.has(id)) {
        changes.push(`Task '${currentTask.title}' will be removed.`);
      }
    } else {
      if (simTask.status !== currentTask.status) {
        changes.push(`Status will revert from '${currentTask.status}' to '${simTask.status}'.`);
      }
      if (simTask.due_local_date !== currentTask.due_local_date) {
        changes.push(`Due date will revert.`);
      }
    }
    if (changes.length > 0) {
      affectedTasks.push({ id, title: currentTask.title, changes });
    }
  }

  const affectedContext: { id: string; summary: string; changes: string[] }[] = [];
  for (const evt of allEvents) {
    if (selectedActionSet.has(evt.action_id) && evt.kind !== 'revert' && !alreadyRevertedEventIds.has(evt.id)) {
      if (['memory_note', 'memory_forgotten', 'draft_created', 'draft_updated', 'note', 'visit', 'contact', 'quote'].includes(evt.kind)) {
        const payload = (evt.payload ?? {}) as Record<string, unknown>;
        let desc = '';
        if (evt.kind === 'memory_note') {
          const raw = String(payload['content'] ?? payload['text'] ?? 'context note');
          desc = `Saved context: "${raw.slice(0, 60)}${raw.length > 60 ? '…' : ''}" will be removed.`;
        } else if (evt.kind === 'memory_forgotten') {
          desc = `Forgotten memory will be restored.`;
        } else if (evt.kind === 'draft_created' || evt.kind === 'draft_updated') {
          desc = `Outward draft (${String(payload['channel'] ?? 'message')}) will be discarded.`;
        } else if (evt.kind === 'note') {
          const raw = String(payload['text'] ?? payload['content'] ?? 'note');
          desc = `Note: "${raw.slice(0, 60)}${raw.length > 60 ? '…' : ''}" will be removed.`;
        } else {
          desc = `${evt.kind.replace(/_/g, ' ')} record will be reverted.`;
        }
        affectedContext.push({
          id: evt.id,
          summary: evt.kind.replace(/_/g, ' '),
          changes: [desc],
        });
      }
    }
  }

  return {
    target_action_id: targetActionId,
    mode,
    selected_action_ids: selectedActionIds,
    affected_event_ids: selectedEventIds,
    affected_entities: affectedEntities,
    affected_tasks: affectedTasks,
    affected_context: affectedContext,
    dependencies: uniqueDeps,
    expected_revision: expectedRevision,
  };
}

export function handleUndoCommit(
  context: LedgerCommandContext,
  allEvents: LedgerEvent[],
  allActions: ActionReceipt[],
  currentState: LedgerProjectionState,
  startSequence: number,
  request: UndoRequest,
): {
  result: CommandResult;
  events: LedgerEvent[];
  nextState?: LedgerProjectionState;
} {
  const preview = computeUndoPreview(
    request.action_id,
    request.mode,
    allActions,
    allEvents,
    currentState,
    request.expected_revision,
  );

  // If there are dependent actions requiring clarification, reject commit until clarified
  if (preview.dependencies.length > 0) {
    return {
      result: {
        status: 'needs_clarification',
        action_id: context.action_id,
        summary: `Undo requires clarification: ${preview.dependencies.length} dependent action(s) from later runs exist.`,
        data: preview,
      },
      events: [],
    };
  }

  if (preview.affected_event_ids.length === 0) {
    return {
      result: {
        status: 'already_applied',
        action_id: context.action_id,
        summary: 'Target action has no active events to revert.',
      },
      events: [],
    };
  }

  // Create revert events for each affected event
  let seq = startSequence;
  const revertEvents: LedgerEvent[] = [];

  for (const eventId of preview.affected_event_ids) {
    const targetEvt = allEvents.find((e) => e.id === eventId);
    if (!targetEvt) continue;

    const revertEvt = createLedgerEvent(context, seq++, {
      entity_id: targetEvt.entity_id,
      kind: 'revert',
      payload: {
        target_event_id: targetEvt.id,
        target_action_id: targetEvt.action_id,
        target_event_kind: targetEvt.kind,
        mode: request.mode,
        group_operation_id: request.client_operation_id,
      },
      reverts_event_id: targetEvt.id,
      provenance: 'stated',
    });
    revertEvents.push(revertEvt);
  }

  // Re-reduce state with the new revert events
  const nextState = rebuildProjections([...allEvents, ...revertEvents]);

  // Identify entities and tasks specifically created by the reverted events
  const revertedEntityIds = new Set<string>();
  const revertedTaskIds = new Set<string>();
  for (const eventId of preview.affected_event_ids) {
    const targetEvt = allEvents.find((e) => e.id === eventId);
    if (!targetEvt) continue;
    if (targetEvt.kind === 'entity_created' && targetEvt.entity_id) {
      revertedEntityIds.add(targetEvt.entity_id);
    }
    if (targetEvt.kind === 'task_created') {
      const p = targetEvt.payload as { task_id?: string };
      if (p?.task_id) revertedTaskIds.add(p.task_id);
    }
  }

  // Preserve existing entities and tasks not created by the undone actions
  // (e.g. seeded entities or external entities present in currentState)
  for (const [id, entity] of currentState.entities) {
    if (!revertedEntityIds.has(id) && !nextState.entities.has(id)) {
      nextState.entities.set(id, entity);
    }
  }
  for (const [id, task] of currentState.tasks) {
    if (!revertedTaskIds.has(id) && !nextState.tasks.has(id)) {
      nextState.tasks.set(id, task);
    }
  }

  return {
    result: {
      status: 'applied',
      action_id: context.action_id,
      affected_resource_ids: preview.selected_action_ids,
      event_ids: revertEvents.map((e) => e.id),
      summary: `Undid ${preview.selected_action_ids.length} action(s) via ${revertEvents.length} revert event(s).`,
      data: {
        reverted_action_ids: preview.selected_action_ids,
        revert_event_ids: revertEvents.map((e) => e.id),
      },
    },
    events: revertEvents,
    nextState,
  };
}
