import type { RecordList } from './types.js';

export const INITIAL_RECORD_LISTS: RecordList[] = [
  {
    id: 'leads',
    name: 'Leads',
    description: 'Active client and prospect records tracked by you and Otis.',
    columns: [
      { id: 'name', name: 'Lead name', type: 'text', width: 200, isCore: true },
      { id: 'status', name: 'Status', type: 'status', width: 120, isCore: true, options: ['new', 'warm', 'hot', 'won', 'cold', 'lost'] },
      { id: 'phone', name: 'Phone', type: 'phone', width: 160, isCore: true },
      { id: 'language', name: 'Language', type: 'text', width: 120, isCore: true },
      { id: 'value', name: 'Deal value', type: 'currency', width: 130 },
      { id: 'assignee', name: 'Assignee', type: 'text', width: 140 },
      { id: 'access', name: 'Access instructions', type: 'text', width: 240 },
      { id: 'notes', name: 'Notes', type: 'text', width: 280 },
    ],
    rows: [
      {
        id: 'lead-1',
        source: 'entity',
        cells: {
          name: 'John Klakney',
          status: 'hot',
          phone: '+1 (91) 356-1329',
          language: 'English',
          value: '$20,000',
          assignee: 'Avi',
          access: 'Gate code 4492 after 6 PM',
          notes: 'Wants full rollout before Q4. Needs contract revision.',
        },
        provenance: { access: 'Observed from conversation on Oct 6' },
      },
      {
        id: 'lead-2',
        source: 'entity',
        cells: {
          name: 'Elena Vance',
          status: 'warm',
          phone: '+1 (91) 356-1773',
          language: 'English',
          value: '$13,000',
          assignee: 'Avi',
          access: 'Main reception desk on 4th floor',
          notes: 'Reviewing budget with finance lead on Thursday.',
        },
        provenance: { status: 'Updated from chat yesterday' },
      },
      {
        id: 'lead-3',
        source: 'entity',
        cells: {
          name: 'Tariq Mansoor',
          status: 'hot',
          phone: '+1 (91) 356-1774',
          language: 'Farsi',
          value: '$35,000',
          assignee: 'Avi',
          access: 'Loading dock B on North entrance',
          notes: 'Prefers communicating in Farsi. Contract signed pending payment.',
        },
        provenance: { language: 'Preferred language captured by Otis' },
      },
      {
        id: 'lead-4',
        source: 'entity',
        cells: {
          name: 'Mark Batch',
          status: 'new',
          phone: '+1 (91) 356-1778',
          language: 'English',
          value: '$10,000',
          assignee: 'Teammate',
          access: '',
          notes: 'Inbound inquiry from landing page. Needs discovery call.',
        },
      },
      {
        id: 'lead-5',
        source: 'entity',
        cells: {
          name: 'Nana Whilten',
          status: 'won',
          phone: '+1 (91) 356-1779',
          language: 'English',
          value: '$18,500',
          assignee: 'Avi',
          access: 'Keycard access at security gate',
          notes: 'Onboarding completed. Renewal scheduled in 6 months.',
        },
      },
      {
        id: 'lead-6',
        source: 'entity',
        cells: {
          name: 'John Bayleys',
          status: 'warm',
          phone: '+1 (91) 353-7736',
          language: 'English',
          value: '$7,500',
          assignee: 'Teammate',
          access: '',
          notes: 'Asked for pilot demo for 5 team members.',
        },
      },
      {
        id: 'lead-7',
        source: 'entity',
        cells: {
          name: 'Leo Geoter',
          status: 'new',
          phone: '+1 (91) 356-1399',
          language: 'English',
          value: '$5,000',
          assignee: 'Avi',
          access: 'Ring bell #3 at entrance',
          notes: 'Met at regional meetup. Follow up next week.',
        },
      },
      {
        id: 'lead-8',
        source: 'entity',
        cells: {
          name: 'Daniel Miramon',
          status: 'cold',
          phone: '+1 (91) 357-7403',
          language: 'English',
          value: '$6,000',
          assignee: 'Avi',
          access: '',
          notes: 'Postponed decisions until next quarter budgeting.',
        },
      },
      {
        id: 'lead-9',
        source: 'entity',
        cells: {
          name: 'Marka Rarsen',
          status: 'won',
          phone: '+1 (91) 356-7778',
          language: 'English',
          value: '$12,000',
          assignee: 'Teammate',
          access: 'Side entrance via badge scanner',
          notes: 'Annual license activated.',
        },
      },
    ],
  },
  {
    id: 'products',
    name: 'Products',
    description: 'Services and packages with conversational calculations.',
    columns: [
      { id: 'name', name: 'Item', type: 'text', width: 220, isCore: true },
      { id: 'category', name: 'Category', type: 'text', width: 140 },
      { id: 'unitPrice', name: 'Unit price', type: 'currency', width: 130 },
      { id: 'quantity', name: 'Quantity', type: 'number', width: 110 },
      {
        id: 'total',
        name: 'Total',
        type: 'calculation',
        width: 140,
        calculation: {
          expression: 'unitPrice * quantity',
          description: 'Unit price × Quantity',
          targetType: 'currency',
        },
      },
      { id: 'notes', name: 'Notes', type: 'text', width: 260 },
    ],
    rows: [
      {
        id: 'prod-1',
        source: 'custom',
        cells: {
          name: 'Business Memory Setup',
          category: 'Implementation',
          unitPrice: '$1,500',
          quantity: '2',
          total: '$3,000',
          notes: 'Workspace provisioning and custom field onboarding',
        },
      },
      {
        id: 'prod-2',
        source: 'custom',
        cells: {
          name: 'Executive Advisory Session',
          category: 'Consulting',
          unitPrice: '$450',
          quantity: '8',
          total: '$3,600',
          notes: 'Weekly strategic sessions with founders',
        },
      },
      {
        id: 'prod-3',
        source: 'custom',
        cells: {
          name: 'Priority Slack Integration',
          category: 'Add-on',
          unitPrice: '$800',
          quantity: '1',
          total: '$800',
          notes: 'Direct channel dispatch hook setup',
        },
      },
    ],
  },
  {
    id: 'tasks',
    name: 'Tasks',
    description: 'Action items linked to entities and conversations.',
    columns: [
      { id: 'title', name: 'Action', type: 'text', width: 240, isCore: true },
      { id: 'status', name: 'Status', type: 'status', width: 120, isCore: true, options: ['open', 'done', 'cancelled'] },
      { id: 'due', name: 'Due date', type: 'date', width: 140 },
      { id: 'assignee', name: 'Assignee', type: 'text', width: 140 },
      { id: 'related', name: 'Related lead', type: 'text', width: 180 },
    ],
    rows: [
      {
        id: 'task-1',
        source: 'task',
        cells: {
          title: 'Send revised quote to Elena Vance',
          status: 'open',
          due: 'Tomorrow',
          assignee: 'Avi',
          related: 'Elena Vance',
        },
      },
      {
        id: 'task-2',
        source: 'task',
        cells: {
          title: 'Prepare Farsi onboarding pack for Tariq',
          status: 'open',
          due: 'Oct 12',
          assignee: 'Avi',
          related: 'Tariq Mansoor',
        },
      },
      {
        id: 'task-3',
        source: 'task',
        cells: {
          title: 'Confirm gate code access for delivery team',
          status: 'done',
          due: 'Oct 6',
          assignee: 'Avi',
          related: 'John Klakney',
        },
      },
    ],
  },
];
