import fs from 'node:fs';
const tab=await(await fetch('http://127.0.0.1:5489/json/new?about:blank',{method:'PUT'})).json();
const ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let seq=0;const pending=new Map();ws.addEventListener('message',e=>{const d=JSON.parse(e.data);if(!d.id)return;const p=pending.get(d.id);pending.delete(d.id);d.error?p.reject(d.error):p.resolve(d.result);});const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>(await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
await call('Page.enable');await call('Page.bringToFront');const results=[];for(const width of [390,1280]){await call('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:false});for(const story of ['disconnected','ready','connected','expired','routing-needed']){await call('Page.navigate',{url:'http://127.0.0.1:5488/iframe.html?id=telegram--'+story+'&viewMode=story'});for(let i=0;i<100;i++){if(await evaluate("Boolean(document.getElementById('storybook-root')?.children.length)"))break;await new Promise(r=>setTimeout(r,100));}await evaluate('document.fonts.ready');await new Promise(r=>setTimeout(r,700));if(story==='ready'||story==='expired'){await evaluate("(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Connect Telegram');if(b)b.click();return true;})()");await new Promise(r=>setTimeout(r,250));}const metrics=await evaluate("({text:document.body.innerText.slice(0,1800),width:innerWidth,scrollWidth:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('button,a')].map(e=>({text:e.textContent.trim(),label:e.getAttribute('aria-label'),color:getComputedStyle(e).color,height:e.getBoundingClientRect().height}))})");const shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(new URL('telegram-'+story+'-'+width+'.png',import.meta.url),Buffer.from(shot.data,'base64'));results.push({story,...metrics});}}
fs.writeFileSync(new URL('009A-telegram-browser-review.json',import.meta.url),JSON.stringify({capturedAt:new Date().toISOString(),scope:'Synthetic production-component Storybook, native Chrome CDP, no external bot navigation',results},null,2));console.log(JSON.stringify(results));ws.close();




