import type {
  CurrentInteraction,
  EntityFile,
  FilePage,
  FollowUpPage,
  HistorySearchResponse,
} from '@otis/contracts';

export const fileSource = {
  event_id: 'event-note',
  message_id: 'message-original',
  actor_user_id: 'user-hunor',
  actor_name: 'Hunor',
  recorded_at: '2026-10-01T08:00:00Z',
  channel: 'web',
};
const page = <T>(items: T[], total = items.length): FilePage<T> => ({
  items,
  total,
  has_more: total > items.length,
  next_cursor: total > items.length ? 'fixture-next' : null,
  availability: 'available',
});
export const fileEntry: CurrentInteraction = {
  interaction_id: 'interaction-note',
  head_event_id: 'event-correction',
  entity_id: 'client-1',
  entity_name: 'North Metals',
  kind: 'note',
  revision: 2,
  occurred_at: '2026-10-01T07:00:00Z',
  sequence: 3,
  payload: { text: 'Prefers afternoon calls. Speaks Farsi.' },
  actor_kind: 'member',
  actor_user_id: 'user-avi',
  actor_name: 'Avi',
  channel: 'web',
  source_message_id: 'message-correction',
  recorded_at: '2026-10-02T09:00:00Z',
  provenance: 'stated',
  original_actor_user_id: 'user-hunor',
  original_actor_name: 'Hunor',
  original_source_message_id: 'message-original',
  original_recorded_at: '2026-10-01T08:00:00Z',
};
/** Synthetic data shared by production stories and mounted behavior checks. */
export function businessFile(): EntityFile {
  const entry = structuredClone(fileEntry);
  return {
    version: 1,
    entity: {
      id: 'client-1',
      name: 'North Metals',
      kind: 'lead',
      status: 'warm',
      assigned_user_id: 'user-avi',
      assigned_name: 'Avi',
      aliases: ['North'],
      merged_from: [{ id: 'client-old', name: 'North Metal Works' }],
    },
    as_of_business_revision: 12,
    facts: page([
      {
        field: 'preferred_language',
        origin_entity_id: 'client-1',
        value: 'Farsi',
        state: 'clear',
        revision: 1,
        candidate_event_ids: [],
        source: fileSource,
      },
    ]),
    timeline: page([entry], 31),
    notes: page([entry], 31),
    quotes: page([
      {
        ...entry,
        interaction_id: 'quote-1',
        head_event_id: 'quote-1',
        kind: 'quote',
        payload: { amount: 120050, currency: 'EUR', role: 'offered' },
      },
    ]),
    tasks: page([
      {
        id: 'task-1',
        entity_id: 'client-1',
        title: 'Send revised samples',
        status: 'open',
        revision: 1,
        assignee_user_id: 'user-avi',
        assignee_name: 'Avi',
        due_kind: 'date',
        due_local_date: '2026-10-01',
        due_instant: null,
        due_timezone: 'Europe/Bucharest',
        snooze_until: null,
        overdue: true,
        source: fileSource,
      },
    ]),
    contacts: page([
      {
        id: 'contact-1',
        workspace_id: 'ws-1',
        entity_id: 'client-1',
        method: 'phone',
        value: '+40 721 123 456',
        comparison_key: '+40721123456',
        label: 'Work',
        is_primary: true,
        state: 'active',
        revision: 1,
        source_event_id: 'event-contact',
        original_event_id: 'event-contact',
        updated_at: '2026-10-01',
        source: fileSource,
      },
    ]),
    attachments: page([
      {
        id: 'link-1',
        entity_id: 'client-1',
        media_id: 'media-voice',
        label: 'Client call',
        format: 'audio/ogg',
        retained: 1,
        media_state: 'ready',
        link_state: 'active',
        revision: 1,
        annotation_revision: 1,
        transcript: 'Quote was 4000 EUR.',
        original_transcript: 'Quote was 400 EUR.',
        correction_message_id: 'message-correction',
        corrected_at: '2026-10-02T09:00:00Z',
        corrector_name: 'Avi',
        source: fileSource,
      },
      {
        id: 'link-2',
        entity_id: 'client-1',
        media_id: 'media-pdf',
        label: 'October quote.pdf',
        filename: 'October quote.pdf',
        format: 'application/pdf',
        retained: 1,
        media_state: 'ready',
        link_state: 'active',
        revision: 1,
        annotation_revision: 0,
        extraction_state: 'needs_visual',
        extraction_error: 'Little readable text was found.',
        source: fileSource,
      },
    ]),
    drafts: page([
      {
        id: 'draft-1',
        content_text: 'Hello, the revised samples will be ready on Friday.',
        source: fileSource,
      },
    ]),
    memory: page([{ id: 'memory-1', content: 'Only call in the afternoon.', source: fileSource }]),
    reminders: page([]),
    history: page([
      {
        id: 'event-note',
        entity_id: 'client-1',
        kind: 'note',
        sequence: 1,
        payload: { text: 'Prefers morning calls.' },
        occurred_at: '2026-10-01T07:00:00Z',
        supersedes_event_id: null,
        reverts_event_id: null,
        is_reverted: false,
        interaction_id: 'interaction-note',
        current_head_event_id: 'event-correction',
        source: fileSource,
      },
    ]),
    last_contact: '2026-10-01T07:00:00Z',
    coverage: { bounded: true, partial_sections: ['timeline', 'notes'], unavailable_sections: [] },
  };
}
export function followUpPage(): FollowUpPage {
  return {
    rows: [
      {
        id: 'rule-1',
        entity_id: null,
        text: 'Review this week’s follow-ups',
        timezone: 'Europe/Bucharest',
        channel: 'web',
        spec: { kind: 'weekly', weekdays: [1, 3], local_time: '09:30' },
        status: 'active',
        revision: 1,
        next_due: '2026-10-12T06:30:00Z',
        last_delivered_at: null,
        actor_user_id: 'user-avi',
        actor_name: 'Avi',
        source_message_id: 'message-original',
        recorded_at: '2026-10-01T08:00:00Z',
        source_channel: 'web',
      },
    ],
    total: 1,
    as_of_business_revision: 12,
    has_more: false,
    next_cursor: null,
  };
}
export function historyMatches(): HistorySearchResponse {
  return {
    version: 1,
    items: [
      {
        message_id: 'message-original',
        inbound_message_id: 'inbound-original',
        chat_id: 'chat-1',
        chat_title: 'North Metals samples',
        author_user_id: 'user-hunor',
        author_name: 'Hunor',
        source_kind: 'member',
        recorded_at: '2026-10-01T08:00:00Z',
        sequence: 1,
        excerpt: 'We promised the copper sample for Friday.',
        source_available: true,
      },
    ],
    total: 2,
    has_more: true,
    next_cursor: 'fixture-next',
    coverage: { mode: 'chronological', bounded: true, index_complete: true },
  };
}
